// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jiyjlqibnyxmcotcdbzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppeWpscWlibnl4bWNvdGNkYnpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0ODY0NDcsImV4cCI6MjA3MDA2MjQ0N30.OY_67QV7etSRuR2q4fUNlj3gneHqFia296xhogFwask";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});